### ISSUE TITLE
Как продвигается процесс перевода?

### ISSUE THREAD

**Issue by anvdev** [AlexanderOnischuk/Houdini16.0-Help-Russian#2]

**Comment by AlexanderOnischuk** [comment]
Пока никак.
Для начала нужно получить разрешение на перевод документации.
В случае одобрения скачать полностью документацию и сделать обьявление по всем каналам(форумы, вконтакт, фейсбук...) о наборе желающих переводчиков. Одному долго будет.
Пока что на это нет ни времени и желания :(

**Comment by anvdev** [comment]
Если хотите, присоединяйтесь ко мне. Но требования к пониманию материала предъявляю высокие.

Уже переведена и опубликована большая часть раздела VEX. На очереди груминг, HScript и основы.
houdinihelp.ru

**Comment by AlexanderOnischuk** [comment]
Интересно.
Надеюсь на сотрудничество в будущем.
В SideFX дали добро на публикацию?
Еще вопрос: перевод в какой программе делаете?
Видел [создали свой репозиторий](https://github.com/anvdev/HoudiniHelpEn).
У меня в планах был процесс проще: создание полной копии документации (как есть) и прямой перевод файлов в HTML-редакторе типа Adobe Dreamweaver.

**Comment by anvdev** [comment]
Переводить HTML, вы серьезно? SESI поменяет css или движок разметки, что тогда делать будете? Я перевожу исходные файлы, а работает все это на flask + nginx. Сами материалы сильно оптимизированы, чтобы сайт моментально загружался.

Обмениваться переводами не собираюсь, так как не вижу смысла. Вы можете присоединиться к переводу. Все технические вопросы уже решены, сайт в данный момент индексируется. Добро от SESI не требуется.

Как вы могли заметить, тот репозиторий с постфиксом En, а в описании сказано, что в нем исправления ошибок для основной справки SideFX. Репозиторий русской справки существует давно и он приватный.
